export const GET_ADD_VALUES = "GET_ADD_VALUES";
export const GET_ADD_VALUES_SUCCESS = "GET_ADD_VALUES_SUCCESS";
export const GET_ADD_VALUES_FAILURE = "GET_ADD_VALUES_FAILURE";
export const UPDATE_ADD_VALUES = "UPDATE_ADD_VALUES";
export const UPDATE_ADD_VALUES_SUCCESS = "UPDATE_ADD_VALUES_SUCCESS";
export const UPDATE_ADD_VALUES_FAILURE = "UPDATE_ADD_VALUES_FAILURE";