export const cases = [
    'Regular Glass',
    'Privacy Glass',
    'Top Glass',
    'Silicone',
    'Punjab Case',
    'OVO Case',
    'Jatt Life Case',
    'Clear Case',
    'Clear Coat'
  ]
  export const models = [
    { 
      brand: 'Apple', 
    models: [
  'Iphone 14 pro max',
  'Iphone 14 pro',
  'Iphone 14',
  'Iphone 13 pro max',
  'Iphone 13 pro',
  'Iphone 13',
  'Iphone 13 mini',
  'Iphone 12 pro max',
  'Iphone 12 pro',
  'Iphone 12',
  'Iphone 12 mini',
  'Iphone SE (2nd generation)',
  'Iphone 11 Pro Max',
  'Iphone 11 Pro',
  'Iphone 11',
  'Iphone XS Max',
  'Iphone XS',
  'Iphone XR',
  'Iphone X',
  'Iphone 8 Plus',
  'Iphone 8',
  'Iphone 7 Plus',
  'Iphone 7',
  'Iphone SE (1st generation)',
  'Iphone 6s Plus',
  'Iphone 6s',
  'Iphone 6 Plus',
] 
    },
    { 
      brand: 'Samsung', 
      models: [
        'Galaxy S23',
        'Galaxy 23 Ultra',
        'Galaxy Note 22 Ultra',
        'Galaxy Note 22',
        'Galaxy S22 Ultra',
        'Galaxy S22+',
        'Galaxy S22',
        'Galaxy Note 21 Ultra',
        'Galaxy Note 21',
        'Galaxy S21 Ultra',
        'Galaxy S21+',
        'Galaxy S21',
        'Galaxy Note 20 Ultra',
        'Galaxy Note 20',
        'Galaxy S20 Ultra',
        'Galaxy S20+',
        'Galaxy S20',
        'Galaxy Note 10+',
        'Galaxy Note 10',
        'Galaxy S10+',
        'Galaxy S10',
        'Galaxy S10e',
        'Galaxy Note 9',
        'Galaxy S9+',
      ] 
    }
  ]
export const silicone = [
  'Black',
  'Rose Gold',
  'White',
  'Yellow',
  'Red',
  'Navy',
  'Hot Pink',
  'Baby Blue',
  'Blue',
  'Midnight Green',
  'Hunter Green',
  'Light Pink',
  'Purple',
  'Orange',
  'Gray',
  'Brown',
  'Wine',
]