export const cases = [
  'Regular Glass',
  'Privacy Glass',
  'Top Glass',
  'Silicone',
  'Punjab Case',
  'OVO Case',
  'Jatt Life Case',
  'Tp Clear',
  'Clear Coat',
  'Silicone-Red',
  'Silicone-Rose Gold',
  'Silicone-Peach',
  'Silicone-Black',
  'Silicone-Purple',
  'Silicone-Green',
  'Silicone-Deep Blue',
  'Silicone-Pink',
  'Silicone-Light Blue',
  'Silicone-Blue',
  'Silicone-Light Purple',
  'Silicone-Navy Blue'
]

 
export const silicone = [
  'Black',
  'Rose Gold',
  'White',
  'Yellow',
  'Red',
  'Navy',
  'Hot Pink',
  'Baby Blue',
  'Blue',
  'Midnight Green',
  'Hunter Green',
  'Light Pink',
  'Purple',
  'Orange',
  'Gray',
  'Brown',
  'Wine',
]