export const modelOptions = [
  {
    label: "APPLE",
    options: [
      { label: "IPHONE 14", value: "IPHONE 14" },
      { label: "IPHONE 14 PRO", value: "IPHONE 14 PRO" },
      { label: "IPHONE 14 PRO MAX", value: "IPHONE 14 PRO MAX" },
      { label: "IPHONE 13", value: "IPHONE 13" },
      { label: "IPHONE 13 PRO", value: "IPHONE 13 PRO" },
      { label: "IPHONE 13 PRO MAX", value: "IPHONE 13 PRO MAX" },
      { label: "IPHONE 13 MINI", value: "IPHONE 13 MINI" },
      { label: "IPHONE 12", value: "IPHONE 12" },
      { label: "IPHONE 12 PRO", value: "IPHONE 12 PRO" },
      { label: "IPHONE 12 PRO MAX", value: "IPHONE 12 PRO MAX" },
      { label: "IPHONE 12 MINI", value: "IPHONE 12 MINI" },
      { label: "IPHONE 11", value: "IPHONE 11" },
      { label: "IPHONE 11 PRO", value: "IPHONE 11 PRO" },
      { label: "IPHONE 11 PRO MAX", value: "IPHONE 11 PRO MAX" },
      { label: "IPHONE X", value: "IPHONE X" },
      { label: "IPHONE XS", value: "IPHONE XS" },
      { label: "IPHONE XS MAX", value: "IPHONE XS MAX" },
      { label: "IPHONE 8 PLUS", value: "IPHONE 8 PLUS" },
      { label: "IPHONE 8", value: "IPHONE 8" },
      { label: "IPHONE 7", value: "IPHONE 7" },
      { label: "IPHONE 7 PLUS", value: "IPHONE 7 PLUS" },
      { label: "IPHONE 6", value: "IPHONE 6" },
      { label: "IPHONE 6S", value: "IPHONE 6S" },
      { label: "IPHONE 6 PLUS", value: "IPHONE 6 PLUS" },
      { label: "IPHONE 6S PLUS", value: "IPHONE 6S PLUS" },
      { label: "AIRPODS", value: "AIRPODS" },
      { label: "AIRPODS 2", value: "AIRPODS 2" },
      { label: "AIRPODS PRO", value: "AIRPODS PRO" },
      { label: "AIRPODS PRO 2", value: "AIRPODS PRO 2" },
      { label: "AIRPODS 3", value: "AIRPODS 3" },
      { label: "PENCIL", value: "PENCIL" },
      { label: "PENCIL 2", value: "PENCIL 2" },
      { label: "WATCH", value: "WATCH" },
    ],
  },
  {
    label: "SAMSUNG",
    options: [
      { label: "S23", value: "S23" },
      { label: "S23 PLUS", value: "S23 PLUS" },
      { label: "S23 ULTRA", value: "S23 ULTRA" },
      { label: "S20", value: "S20" },
      { label: "S20 FE", value: "S20 FE" },
      { label: "S20 PLUS", value: "S20 PLUS" },
      { label: "S20 ULTRA", value: "S20 ULTRA" },
      { label: "S21", value: "S21" },
      { label: "S21 FE", value: "S21 FE" },
      { label: "S21 PLUS", value: "S21 PLUS" },
      { label: "S21 ULTRA", value: "S21 ULTRA" },
      { label: "S22", value: "S22" },
      { label: "S22 FE", value: "S22 FE" },
      { label: "S22 PLUS", value: "S22 PLUS" },
      { label: "S22 ULTRA", value: "S22 ULTRA" },
      { label: "NOTE 10", value: "NOTE 10" },
      { label: "NOTE 10 PLUS", value: "NOTE 10 PLUS" },
      { label: "NOTE 10 ULTRA", value: "NOTE 10 ULTRA" },
      { label: "NOTE 20", value: "NOTE 20" },
      { label: "NOTE 20 PLUS", value: "NOTE 20 PLUS" },
      { label: "NOTE 20 ULTRA", value: "NOTE 20 ULTRA" },
      { label: "NOTE 21", value: "NOTE 21" },
      { label: "NOTE 21 PLUS", value: "NOTE 21 PLUS" },
      { label: "NOTE 21 ULTRA", value: "NOTE 21 ULTRA" },
      { label: "NOTE 8", value: "NOTE 8" },
      { label: "NOTE 9", value: "NOTE 9" },
      { label: "S5", value: "S5" },
      { label: "S6", value: "S6" },
      { label: "S7", value: "S7" },
      { label: "S8", value: "S8" },
      { label: "S8 PLUS", value: "S8 PLUS" },
      { label: "S9", value: "S9" },
      { label: "S9 PLUS", value: "S9 PLUS" },
      { label: "S10", value: "S10" },
      { label: "S10 PLUS", value: "S10 PLUS" },
      { label: "A01", value: "A01" },
      { label: "A01 CORE", value: "A01 CORE" },
      { label: "A02", value: "A02" },
      { label: "A03", value: "A03" },
      { label: "A03 CORE", value: "A03 CORE" },
      { label: "A10", value: "A10" },
      { label: "A10S", value: "A10S" },
      { label: "A11", value: "A11" },
      { label: "A12", value: "A12" },
      { label: "A13", value: "A13" },
      { label: 'A14', value: 'A14'},
      { label: "A20", value: "A20" },
      { label: "A20S", value: "A20S" },
      { label: "A21", value: "A21" },
      { label: "A21S", value: "A21S" },
      { label: "A22", value: "A22" },
      { label: "A23", value: "A23" },
      { label: "A32", value: "A32" },
      { label: "A33", value: "A33" },
      { label: "A50", value: "A50" },
      { label: "A51", value: "A51" },
      { label: "A52 5G", value: "A52 5G" },
      { label: "A53", value: "A53" },
      { label: "A70", value: "A70" },
      { label: "A71", value: "A71" },
      { label: "GALAXY BUDS", value: "GALAXY BUDS" },
    ],
  },
  {
    label: "GOOGLE",
    options: [
      { label: "PIXEL 6", value: "PIXEL 6" },
      { label: "PIXEL 6A", value: "PIXEL 6A" },
      { label: "PIXEL 6 PRO", value: "PIXEL 6 PRO" },
      { label: "PIXEL 7", value: "PIXEL 7" },
      { label: "PIXEL 7 PRO", value: "PIXEL 7 PRO" },
      { label: "PIXEL 5", value: "PIXEL 5" },
      { label: "PIXEL 4A", value: "PIXEL 4A" },
      { label: "PIXEL 4A 5G", value: "PIXEL 4A 5G" },
      { label: "PIXEL 4", value: "PIXEL 4" },
      { label: "PIXEL 4 XL", value: "PIXEL 4 XL" },
      { label: "PIXEL 3", value: "PIXEL 3" },
      { label: "PIXEL 3 XL", value: "PIXEL 3 XL" },
      { label: "PIXEL 3A", value: "PIXEL 3A" },
      { label: "PIXEL 3A XL", value: "PIXEL 3A XL" },
      { label: "PIXEL 2", value: "PIXEL 2" },
      { label: "PIXEL 2 XL", value: "PIXEL 2 XL" },
      { label: "PIXEL 2A", value: "PIXEL 2A" },
      { label: "PIXEL 2A XL", value: "PIXEL 2A XL" },
    ],
  },
  {
    label: "ALCATEL",
    options: [
      { label: "ALCATEL 1", value: "ALCATEL 1" },
      { label: "GO FLIP 3", value: "GO FLIP 3" },
      { label: "INSIGHT", value: "INSIGHT" },
    ],
  },
  {
    label: "ZTE",
    options: [
      { label: "BLADE A3 LITE", value: "BLADE A3 LITE" },
      { label: "BLADE A31 LITE", value: "BLADE A31 LITE" },
      { label: "BLADE A7P", value: "BLADE A7P" },
      { label: "BLADE L210", value: "BLADE L210" },
      { label: "GRAND X VIEW 4", value: "GRAND X VIEW 4" },
      { label: "CMBAL 2", value: "CMBAL 2" },
    ],
  },
];