const brands = [
    {
      name: 'APPLE',
      models: [
        'IPHONE 14',
        'IPHONE 14 PRO',
        'IPHONE 14 PRO MAX',
        'IPHONE 13',
        'IPHONE 13 PRO',
        'IPHONE 13 PRO MAX',
        'IPHONE 13 MINI',
        'IPHONE 12',
        'IPHONE 12 PRO',
        'IPHONE 12 PRO MAX',
        'IPHONE 12 MINI',
        'IPHONE 11',
        'IPHONE 11 PRO',
        'IPHONE 11 PRO MAX',
        'IPHONE X',
        'IPHONE XS',
        'IPHONE XS MAX',
        'IPHONE 8 PLUS',
        'IPHONE 8',
        'IPHONE 7',
        'IPHONE 7 PLUS',
        'IPHONE 6',
        'IPHONE 6S',
        'IPHONE 6 PLUS',
        'IPHONE 6S PLUS',
      ],
      accessories: [
        'AIRPODS',
        'AIRPODS 2',
        'AIRPODS PRO',
        'AIRPODS PRO 2',
        'AIRPODS 3',
        'PENCIL',
        'PENCIL 2',
        'WATCH',
      ],
    },
    {
      name: 'SAMSUNG',
      models: [
        'S23',
        'S23 PLUS',
        'S23 ULTRA',
        'S20',
        'S20 FE',
        'S20 PLUS',
        'S20 ULTRA',
        'S21',
        'S21 FE',
        'S21 PLUS',
        'S21 ULTRA',
        'S22',
        'S22 FE',
        'S22 PLUS',
        'S22 ULTRA',
        'NOTE 10',
        'NOTE 10 PLUS',
        'NOTE 10 ULTRA',
        'NOTE 20',
        'NOTE 20 PLUS',
        'NOTE 20 ULTRA',
        'NOTE 21',
        'NOTE 21 PLUS',
        'NOTE 21 ULTRA',
        'NOTE 8',
        'NOTE 9',
        'S5',
        'S6',
        'S7',
        'S8',
        'S8 PLUS',
        'S9',
        'S9 PLUS',
        'S10',
        'S10 PLUS',
        'A01',
        'A01 CORE',
        'A02',
        'A03',
        'A03 CORE',
        'A10',
        'A10S',
        'A11',
        'A12',
        'A13',
        'A20',
        'A20S',
        'A21',
        'A21S',
        'A22',
        'A23',
        'A32',
        'A33',
        'A50',
        'A51',
        'A52 5G',
        'A70',
        'A71',
      ],
      accessories: ['GALAXY BUDS'],
    },
    {
      name: 'GOOGLE',
      models: [
        'PIXEL 6',
        'PIXEL 6A',
        'PIXEL 6 PRO',
        'PIXEL 7',
        'PIXEL 7 PRO',
        'PIXEL 5',
        'PIXEL 4A',
        'PIXEL 4A 5G',
        'PIXEL 4',
        'PIXEL 4 XL',
        'PIXEL 3',
        'PIXEL 3 XL',
        'PIXEL 3A',
        'PIXEL 3A XL',
        'PIXEL 2',
        'PIXEL 2 XL',
        'PIXEL 2A',
        'PIXEL 2A XL',
      ],
      accessories: [],
    },
    {
      name: 'ALCATEL',
      models: ['ALCATEL 1', 'GO FLIP 3', 'INSIGHT'],
      accessories: [],
    },
    {
      name: 'ZTE',
      models: [
        'BLADE A3 LITE',
        'BLADE A31 LITE',
        'BLADE A7P',
        'BLADE L210',
        'CMBAL 2',
      ],
      accessories: [],
    },
  ]

  export default brands