export const GET_MODELS = "GET_MODELS";
export const GET_MODELS_SUCCESS = "GET_MODELS_SUCCESS";
export const GET_MODELS_FAILURE = "GET_MODELS_FAILURE";
export const UPDATE_MODELS = "UPDATE_MODELS";
export const UPDATE_MODELS_SUCCESS = "UPDATE_MODELS_SUCCESS";
export const UPDATE_MODELS_FAILURE = "UPDATE_MODELS_FAILURE";
