// orders
export const FETCH_ORDERS = 'FETCH_ORDERS'
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE'

export const ADD_NEW_ORDERS = 'ADD_NEW_ORDERS'
export const ADD_NEW_ORDERS_SUCCESS = 'ADD_NEW_ORDERS_SUCCESS'
export const ADD_NEW_ORDERS_FAILURE = 'ADD_NEW_ORDERS_FAILURE'

export const UPDATE_ORDERS = 'UPDATE_ORDERS'
export const UPDATE_ORDERS_SUCCESS = 'UPDATE_ORDERS_SUCCESS'
export const UPDATE_ORDERS_FAILURE = 'UPDATE_ORDERS_FAILURE'

export const DELETE_ORDERS = 'DELETE_ORDERS'
export const DELETE_ORDERS_SUCCESS = 'DELETE_ORDERS_SUCCESS'
export const DELETE_ORDERS_FAILURE = 'DELETE_ORDERS_FAILURE'
